// 
//  ChannelsInterfaces.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol ChannelsDependencyInterface {
    func makeChannelsView() -> ChannelsViewInterface
}

// Router
protocol ChannelsRouterInterface: ViewRouterInterface {
}

// ViewController
protocol ChannelsViewInterface: ViewInterface {
    func reloadData()
    func setLoadingVisible(_ visible: Bool)
}

// Presenter
protocol ChannelsPresenterInterface: PresenterInterface {
    func numberOfSections() -> Int
    func numberOfCategories() -> Int
    func numberOfNewEpisodes() -> Int
    func categoryAtIndex(index: Int) -> Category
    func newEpisodeAt(index: Int) -> Media
    func channelAtIndex(index: Int) -> Channel
    func refreshAllChannels()
    func fetchChannelsInfo()
}

// Interactor
protocol ChannelsInteractorInterface {
    func fetchNewEpisodes(loadFromCache: Bool, completion: @escaping (Result<[Media], NetworkError>) -> Void)
    func fetchChannels(loadFromCache: Bool, completion: @escaping (Result<[Channel], NetworkError>) -> Void)
    func fetchCategories(completion: @escaping (Result<[Category], NetworkError>) -> Void)
}

enum ChannelSection: Int {
    case newEpisodes
    case channels
    case categories
}
