// 
//  ChannelsDependency.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ChannelsDependency: ChannelsDependencyInterface {
    // MARK: - Module Setup

    func makeChannelsView() -> ViewInterface {
        let view = ChannelsViewController()

        let interactor = ChannelsInteractor()
        let categoriesInteractor = CategoriesInteractor()
        
        let navigationController = NavigationController()
        
        let router = ChannelsRouter(rootController: navigationController)
        router.setRootView(view, animated: false)
        
        let presenter = ChannelsPresenter(view: view,
                                          interactor: interactor,
                                          categoriesInteractor: categoriesInteractor,
                                          router: router)
        view.presenter = presenter

        return router.toController()
    }
}
