// 
//  ChannelsRouter.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ChannelsRouter: NavigationRouter {
}

// MARK: - ChannelsRouterInterface

extension ChannelsRouter: ChannelsRouterInterface {
}
