// 
//  ChannelsPresenter.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ChannelsPresenter {
    // MARK: - Private Properties

    private unowned let view: ChannelsViewInterface
    private let interactor: ChannelsInteractorInterface
    private let categoriesInteractor: CategoriesInteractorInterface
    private let router: ChannelsRouterInterface

    private var newEpisodes = [Media]()
    private var listChannels = [Channel]()
    private var categories = [Category]()
    
    private var isLoading = false {
        didSet {
            view.setLoadingVisible(isLoading)
        }
    }
    
    private let dispatchGroup = DispatchGroup()
    
    // MARK: - LifeCycle

    init(view: ChannelsViewInterface,
         interactor: ChannelsInteractorInterface,
         categoriesInteractor: CategoriesInteractorInterface,
         router: ChannelsRouterInterface) {
        self.view = view
        self.interactor = interactor
        self.categoriesInteractor = categoriesInteractor
        self.router = router
    }

    func viewDidLoad() {
        fetchNewEpisodesFromCache()
    }
    
    private func fetchNewEpisodesFromCache() {
        interactor.fetchNewEpisodes(loadFromCache: true) { [weak self] (result) in
            guard let self = self else { return }
            switch result {
            case .success(let medias):
                self.newEpisodes = medias
                self.view.reloadData()
            case .failure(let error):
                Logger.shared.error(object: error)
            }
            self.fetchChannelsInfo()
        }
    }
    
    private func fetchNewEpisode() {
        dispatchGroup.enter()
        interactor.fetchNewEpisodes(loadFromCache: false) { [weak self] (result) in
            guard let self = self else { return }
            switch result {
            case .success(let medias):
                self.newEpisodes = medias
            case .failure(let error):
                Logger.shared.error(object: error)
            }
            self.dispatchGroup.leave()
        }
    }
    
    private func fetchListChannels() {
        dispatchGroup.enter()
        interactor.fetchChannels(loadFromCache: false) { [weak self] (result) in
            guard let self = self else { return }
            switch result {
            case .success(let channels):
                self.listChannels = channels
            case .failure(let error):
                Logger.shared.error(object: error)
            }
            self.dispatchGroup.leave()
        }
    }
    
    private func fetchListCategories() {
        dispatchGroup.enter()
        categoriesInteractor.fetchCategories(fromCache: false) { [weak self] (result) in
            guard let self = self else { return }
            switch result {
            case .success(let categories):
                self.categories = categories
            case .failure(let error):
                Logger.shared.error(object: error)
            }
            self.dispatchGroup.leave()
        }
    }
}

// MARK: - ChannelsPresenterInterface

extension ChannelsPresenter: ChannelsPresenterInterface {
    
    func numberOfSections() -> Int {
        return listChannels.count + (categories.isEmpty ? 0 : 1) + (newEpisodes.isEmpty ? 0 : 1)
    }
    
    func numberOfCategories() -> Int {
        return categories.count
    }
    
    func numberOfNewEpisodes() -> Int {
        return newEpisodes.count
    }
    
    func categoryAtIndex(index: Int) -> Category? {
        return categories[safe: index]
    }
    
    func newEpisodeAt(index: Int) -> Media? {
        return newEpisodes[safe: index]
    }
    
    func channelAtIndex(index: Int) -> Channel? {
        return listChannels[safe: index]
    }
    
    func listChannelItems() -> [Channel] {
        return listChannels
    }
    
    func listNewEpisodes() -> [Media] {
        return newEpisodes
    }
    
    func refreshAllChannels() {
        newEpisodes.removeAll()
        listChannels.removeAll()
        categories.removeAll()
        fetchChannelsInfo()
    }
    
    func fetchChannelsInfo() {
        isLoading = true
        
        fetchNewEpisode()
        fetchListChannels()
        fetchListCategories()
        
        dispatchGroup.notify(queue: .main) { [weak self] in
            guard let self = self else { return }
            self.isLoading = false
            self.view.reloadData()
        }
    }
}
