// 
//  ChannelsDependency.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/9/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ChannelsDependency: ChannelsDependencyInterface {
    // MARK: - Module Setup

    func makeChannelsView() -> ChannelsViewInterface {
        let view = ChannelsViewController()

        let interactor = ChannelsInteractor()
        let router = ChannelsRouter(rootController: view)

        let presenter = ChannelsPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter

        return view
    }
}
