// 
//  CategoriesRouter.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CategoriesRouter: ViewRouter {
}

// MARK: - CategoriesRouterInterface

extension CategoriesRouter: CategoriesRouterInterface {
}
