// 
//  CategoriesPresenter.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CategoriesPresenter {
    // MARK: - Private Properties

    private unowned let view: CategoriesViewInterface
    private let interactor: CategoriesInteractorInterface
    private let router: CategoriesRouterInterface

    // MARK: - LifeCycle

    init(view: CategoriesViewInterface,
         interactor: CategoriesInteractorInterface,
         router: CategoriesRouterInterface) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func viewDidLoad() {
    }
}

// MARK: - CategoriesPresenterInterface

extension CategoriesPresenter: CategoriesPresenterInterface {
}
