// 
//  CategoriesDependency.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class CategoriesDependency: CategoriesDependencyInterface {
    // MARK: - Module Setup

    func makeCategoriesView() -> CategoriesViewInterface {
        let view = CategoriesViewController()

        let interactor = CategoriesInteractor()
        let router = CategoriesRouter(rootController: view)

        let presenter = CategoriesPresenter(view: view, interactor: interactor, router: router)
        view.presenter = presenter

        return view
    }
}
