// 
//  CategoriesViewController.swift
//  MindValley
//
//  Created by Canh Tran Wizeline on 4/10/20.
//  Copyright © 2020 CanhTran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

// Displaying the list episoded belonged to current category
final class CategoriesViewController: BaseViewController {
    // MARK: - Public Properties

    var presenter: CategoriesPresenterInterface!

    // MARK: - LifeCycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        presenter.viewDidLoad()
    }

    // MARK: - Setup

    private func setupView() {
    }
}

// MARK: - CategoriesViewInterface

extension CategoriesViewController: CategoriesViewInterface {
}
